/**
 * Mirrors the server/forms audit event enums
 */
export enum CommonAuditEvent {
  CONFIRM_PRIVACY_SCREEN = 'CONFIRM_PRIVACY_SCREEN',
}

export enum SentencePlanAuditEvent {
  VIEW_PLAN_OVERVIEW = 'VIEW_PLAN_OVERVIEW',
  VIEW_SELECT_AREA_OF_NEED = 'VIEW_SELECT_AREA_OF_NEED',
  PRINT_ALL_GOALS = 'PRINT_ALL_GOALS',
  VIEW_CREATE_GOAL = 'VIEW_CREATE_GOAL',
  CREATE_GOAL = 'CREATE_GOAL',
  VIEW_CHANGE_GOAL = 'VIEW_CHANGE_GOAL',
  EDIT_GOAL = 'EDIT_GOAL',
  VIEW_ADD_STEPS = 'VIEW_ADD_STEPS',
  ADD_STEPS = 'ADD_STEPS',
  EDIT_STEPS = 'EDIT_STEPS',
  VIEW_DELETE_GOAL = 'VIEW_DELETE_GOAL',
  DELETE_GOAL = 'DELETE_GOAL',
  EDIT_PLAN_AGREEMENT = 'EDIT_PLAN_AGREEMENT',
  EDIT_PLAN_AGREEMENT_UPDATE = 'EDIT_PLAN_AGREEMENT_UPDATE',
  VIEW_UPDATE_GOAL_AND_STEPS = 'VIEW_UPDATE_GOAL_AND_STEPS',
  EDIT_STEP_PROGRESS = 'EDIT_STEP_PROGRESS',
  VIEW_CONFIRM_GOAL_ACHIEVED = 'VIEW_CONFIRM_GOAL_ACHIEVED',
  EDIT_GOAL_ACHIEVED = 'EDIT_GOAL_ACHIEVED',
  VIEW_CONFIRM_GOAL_REMOVED = 'VIEW_CONFIRM_GOAL_REMOVED',
  EDIT_GOAL_REMOVED = 'EDIT_GOAL_REMOVED',
  VIEW_CONFIRM_RE_ADD_GOAL = 'VIEW_CONFIRM_RE_ADD_GOAL',
  CREATE_RE_ADD_GOAL = 'CREATE_RE_ADD_GOAL',
  VIEW_INACTIVE_GOAL = 'VIEW_INACTIVE_GOAL',
  VIEW_ABOUT_PERSON = 'VIEW_ABOUT_PERSON',
  VIEW_SUPERVISION_PACKAGE = 'VIEW_SUPERVISION_PACKAGE',
  VIEW_PLAN_HISTORY = 'VIEW_PLAN_HISTORY',
  VIEW_PREVIOUS_VERSIONS = 'VIEW_PREVIOUS_VERSIONS',
  VIEW_HISTORIC_PLAN = 'VIEW_HISTORIC_PLAN',
  VIEW_HISTORIC_ASSESSMENT = 'VIEW_HISTORIC_ASSESSMENT',
}

export enum SanAuditEvent {
  VIEW_QUESTION_PAGE = 'VIEW_QUESTION_PAGE',
  VIEW_SECTION_SUMMARY = 'VIEW_SECTION_SUMMARY',
  VIEW_PRACTITIONER_ANALYSIS = 'VIEW_PRACTITIONER_ANALYSIS',
  VIEW_ALL_ANSWERS = 'VIEW_ALL_ANSWERS',
  VIEW_PREVIOUS_VERSIONS = 'VIEW_PREVIOUS_VERSIONS',
  VIEW_HISTORIC_ASSESSMENT = 'VIEW_HISTORIC_ASSESSMENT',
  SAVE_QUESTION_PAGE = 'SAVE_QUESTION_PAGE',
  MARK_SECTION_COMPLETE = 'MARK_SECTION_COMPLETE',
  EDIT_ANSWERS = 'EDIT_ANSWERS',
  PRINT_ASSESSMENT = 'PRINT_ASSESSMENT',
}
