export enum DrugOption {
  amphetamines = 'AMPHETAMINES',
  benzodiazepines = 'BENZODIAZEPINES',
  cannabis = 'CANNABIS',
  cocaine_hydrochloride = 'COCAINE_HYDROCHLORIDE',
  crack_or_cocaine = 'CRACK_OR_COCAINE',
  ecstasy = 'ECSTASY',
  hallucinogens = 'HALLUCINOGENS',
  heroin = 'HEROIN',
  ketamine = 'KETAMINE',
  methadone = 'METHADONE',
  misused_prescribed_drugs = 'MISUSED_PRESCRIBED_DRUGS',
  other_opiates = 'OTHER_OPIATES',
  solvents = 'SOLVENTS',
  spice = 'SPICE',
  steroids = 'STEROIDS',
  other_drugs = 'OTHER_DRUGS',
}
