export const CommonOption = {
  yes: 'YES',
  no: 'NO',
  none_of_these: 'NONE_OF_THESE',
  other: 'OTHER',
  none: 'NONE',
  unknown: 'UNKNOWN',
  no_problems: 'NO_PROBLEMS',
  some_problems: 'SOME_PROBLEMS',
  significant_problems: 'SIGNIFICANT_PROBLEMS',
  full_motivation: 'FULL_MOTIVATION',
  partial_motivation: 'PARTIAL_MOTIVATION',
  no_motivation: 'NO_MOTIVATION',
  na: 'NA',
} as const
