# docker-compose.test-headless.yml is used to spin up the app specifically
# for integration testing in a completely headless deployment.

services:
  ui:
    environment:
      INGRESS_URL: http://ui:3000
      HMPPS_AUTH_URL: http://wiremock:8080/auth
      HMPPS_AUTH_EXTERNAL_URL: http://wiremock:8080/auth

  cypress:
    image: cypress/included:15.0.0
    networks:
      - hmpps
    depends_on:
      - wiremock
      - ui
    environment:
      CYPRESS_BASE_URL: http://ui:3000
      WIREMOCK_URL: 'http://wiremock:8080'
    working_dir: /cypress
    entrypoint: sh
    command: -c "npm i && npx cypress run"
    volumes:
      - ./cypress-package.json:/cypress/package.json
      - ../cypress.config.ts:/cypress/cypress.config.ts
      - ../reporter-config.json:/cypress/reporter-config.json
      - ../integration_tests:/cypress/integration_tests
      - ../test_results:/cypress/test_results
