# `docker-compose.local.yml` defines services that must be run locally
# to support a fully self-contained local development environment.

services:
  wiremock-proxy:
    ports:
      - '8080:8080'

  hmpps-arns-assessment-platform-ui:
    build:
      target: development
    command: npm run start:dev
    volumes:
      - ../:/app:cached
      - node_modules:/app/node_modules
    environment:
      NODE_ENV: development
      NODE_CLUSTER_ENABLED: false
      ENVIRONMENT_NAME: dev
      FEATURE_FLAG_URL: https://feature-toggles-dev.hmpps.service.justice.gov.uk

volumes:
  node_modules:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_node_modules
