export const Question = {
  current_employment_status: 'current_employment_status',
  type_of_employment: 'type_of_employment',
  day_to_day_commitments: 'day_to_day_commitments',
  had_previous_employment_unavailable_for_work: 'had_previous_employment_unavailable_for_work',
  had_previous_employment_actively_looking_for_work: 'had_previous_employment_actively_looking_for_work',
  had_previous_employment_not_looking_for_work: 'had_previous_employment_not_looking_for_work',
  employment_history: 'employment_history',
  employment_sector: 'employment_sector',
  continuous_employment_history_employment_details: 'continuous_employment_history_employment_details',
  changes_often_employment_history_employment_details: 'changes_often_employment_history_employment_details',
  unstable_employment_history_employment_details: 'unstable_employment_history_employment_details',
  unknown_employment_history_employment_details: 'unknown_employment_history_employment_details',
  day_to_day_caring_responsibilities_details: 'day_to_day_caring_responsibilities_details',
  day_to_day_volunteering_responsibilities_details: 'day_to_day_volunteering_responsibilities_details',
  employment_and_education_changes: 'employment_and_education_changes',
  does_not_want_to_answer_details: 'does_not_want_to_answer_details',
  does_not_want_to_make_changes_details: 'does_not_want_to_make_changes_details',
  thinking_about_making_changes_details: 'thinking_about_making_changes_details',
  wants_to_make_changes_needs_help_details: 'wants_to_make_changes_needs_help_details',
  wants_to_make_changes_knows_how_to_details: 'wants_to_make_changes_knows_how_to_details',
  actively_making_changes_details: 'actively_making_changes_details',
  has_made_positive_changes_details: 'has_made_positive_changes_details',
  education_experience: 'education_experience',
  negative_education_experience_details: 'negative_education_experience_details',
  mostly_negative_education_experience_details: 'mostly_negative_education_experience_details',
  positive_and_negative_education_experience_details: 'positive_and_negative_education_experience_details',
  mostly_positive_education_experience_details: 'mostly_positive_education_experience_details',
  positive_education_experience_details: 'positive_education_experience_details',
  employment_experience: 'employment_experience',
  negative_employment_experience_details: 'negative_employment_experience_details',
  mostly_negative_employment_experience_details: 'mostly_negative_employment_experience_details',
  positive_and_negative_employment_experience_details: 'positive_and_negative_employment_experience_details',
  mostly_positive_employment_experience_details: 'mostly_positive_employment_experience_details',
  positive_employment_experience_details: 'positive_employment_experience_details',
  difficulties_reading_writing_numeracy: 'difficulties_reading_writing_numeracy',
  numeracy_difficulty_level: 'numeracy_difficulty_level',
  writing_difficulty_level: 'writing_difficulty_level',
  reading_difficulty_level: 'reading_difficulty_level',
  job_skills: 'job_skills',
  some_job_skills_details: 'some_job_skills_details',
  has_job_skills_details: 'has_job_skills_details',
  professional_qualification: 'professional_qualification',
  professional_qualification_details: 'professional_qualification_details',
  academic_qualification: 'academic_qualification',
  day_to_day_other_commitments_details: 'day_to_day_other_commitments_details',
  day_to_day_child_responsibilities_details: 'day_to_day_child_responsibilities_details',
  employment_education_strengths_protective_factors: 'employment_education_strengths_protective_factors',
  employment_education_linked_to_serious_harm: 'employment_education_linked_to_serious_harm',
  employment_education_linked_to_reoffending: 'employment_education_linked_to_reoffending',
  employment_education_risk_of_reoffending_details: 'employment_education_risk_of_reoffending_details',
  employment_education_no_risk_of_reoffending_details: 'employment_education_no_risk_of_reoffending_details',
  employment_education_no_serious_harm_details: 'employment_education_no_serious_harm_details',
  employment_education_serious_harm_details: 'employment_education_serious_harm_details',
  employment_education_strengths_protective_factors_details:
    'employment_education_strengths_protective_factors_details',
  employment_education_no_strengths_protective_factors_details:
    'employment_education_no_strengths_protective_factors_details',
}
