export enum FrequencyOption {
  ONCE_A_MONTH = 'ONCE_A_MONTH',
  TWO_TO_FOUR_TIMES_A_MONTH= 'TWO_TO_FOUR_TIMES_A_MONTH',
  TWO_TO_THREE_TIMES_A_WEEK= 'TWO_TO_THREE_TIMES_A_WEEK',
  MORE_THAN_FOUR_TIME_A_WEEK= 'MORE_THAN_FOUR_TIME_A_WEEK',
}

export enum AlcoholUnitsOption {
  ONE_TO_TWO_UNITS= 'ONE_TO_TWO_UNITS',
  THREE_TO_FOUR_UNITS= 'THREE_TO_FOUR_UNITS',
  FIVE_TO_SIX_UNITS= 'FIVE_TO_SIX_UNITS',
  SEVEN_TO_NINE_UNITS= 'SEVEN_TO_NINE_UNITS',
  TEN_OR_MORE_UNITS= 'TEN_OR_MORE_UNITS',
}
