export const Option = {
  pending_treatment: 'PENDING_TREATMENT',
  yes_some_difficulties: 'YES_SOME_DIFFICULTIES',
  positive: 'POSITIVE',
  some_negative_aspects: 'SOME_NEGATIVE_ASPECTS',
  negative: 'NEGATIVE',
  optimistic: 'OPTIMISTIC',
  not_sure: 'NOT_SURE',
  not_optimistic: 'NOT_OPTIMISTIC',
  accommodation: 'ACCOMMODATION',
  employment: 'EMPLOYMENT',
  faith_or_religion: 'FAITH_OR_RELIGION',
  community: 'COMMUNITY',
  medication_or_treatment: 'MEDICATION_OR_TREATMENT',
  money: 'MONEY',
  relationships: 'RELATIONSHIPS',
  yes_significant_difficulties: 'YES_SIGNIFICANT_DIFFICULTIES',
  yes_ongoing_severe: 'YES_ONGOING_SEVERE',
  yes_ongoing: 'YES_ONGOING',
  yes_in_the_past: 'YES_IN_THE_PAST',
} as const
