export const Question = {
  health_wellbeing_physical_health_condition: 'health_wellbeing_physical_health_condition',
  health_wellbeing_physical_health_condition_yes_details: 'health_wellbeing_physical_health_condition_yes_details',
  health_wellbeing_mental_health_condition_yes_ongoing_severe_details:
    'health_wellbeing_mental_health_condition_yes_ongoing_severe_details',
  health_wellbeing_mental_health_condition_yes_ongoing_details:
    'health_wellbeing_mental_health_condition_yes_ongoing_details',
  health_wellbeing_mental_health_condition_yes_in_the_past_details:
    'health_wellbeing_mental_health_condition_yes_in_the_past_details',
  health_wellbeing_mental_health_condition: 'health_wellbeing_mental_health_condition',
  health_wellbeing_prescribed_medication_physical_conditions:
    'health_wellbeing_prescribed_medication_physical_conditions',
  health_wellbeing_prescribed_medication_mental_conditions: 'health_wellbeing_prescribed_medication_mental_conditions',
  health_wellbeing_psychiatric_treatment: 'health_wellbeing_psychiatric_treatment',
  health_wellbeing_head_injury_or_illness: 'health_wellbeing_head_injury_or_illness',
  health_wellbeing_neurodiverse_conditions_yes_details: 'health_wellbeing_neurodiverse_conditions_yes_details',
  health_wellbeing_neurodiverse_conditions: 'health_wellbeing_neurodiverse_conditions',
  health_wellbeing_learning_difficulties_yes_significant_difficulties_details:
    'health_wellbeing_learning_difficulties_yes_significant_difficulties_details',
  health_wellbeing_learning_difficulties_yes_some_difficulties_details:
    'health_wellbeing_learning_difficulties_yes_some_difficulties_details',
  health_wellbeing_learning_difficulties: 'health_wellbeing_learning_difficulties',
  health_wellbeing_coping_day_to_day_life: 'health_wellbeing_coping_day_to_day_life',
  health_wellbeing_attitude_towards_self: 'health_wellbeing_attitude_towards_self',
  health_wellbeing_self_harmed_yes_details: 'health_wellbeing_self_harmed_yes_details',
  health_wellbeing_self_harmed: 'health_wellbeing_self_harmed',
  health_wellbeing_attempted_suicide_or_suicidal_thoughts_yes_details:
    'health_wellbeing_attempted_suicide_or_suicidal_thoughts_yes_details',
  health_wellbeing_attempted_suicide_or_suicidal_thoughts: 'health_wellbeing_attempted_suicide_or_suicidal_thoughts',
  health_wellbeing_outlook: 'health_wellbeing_outlook',
  health_wellbeing_positive_factors_other_details: 'health_wellbeing_positive_factors_other_details',
  health_wellbeing_positive_factors: 'health_wellbeing_positive_factors',
  health_wellbeing_changes_made_changes_details: 'health_wellbeing_changes_made_changes_details',
  health_wellbeing_changes_making_changes_details: 'health_wellbeing_changes_making_changes_details',
  health_wellbeing_changes_want_to_make_changes_details: 'health_wellbeing_changes_want_to_make_changes_details',
  health_wellbeing_changes_needs_help_to_make_changes_details:
    'health_wellbeing_changes_needs_help_to_make_changes_details',
  health_wellbeing_changes_thinking_about_making_changes_details:
    'health_wellbeing_changes_thinking_about_making_changes_details',
  health_wellbeing_changes_does_not_want_to_make_changes_details:
    'health_wellbeing_changes_does_not_want_to_make_changes_details',
  health_wellbeing_changes_does_not_want_to_answer_details: 'health_wellbeing_changes_does_not_want_to_answer_details',
  health_wellbeing_changes: 'health_wellbeing_changes',
  health_wellbeing_practitioner_analysis_strengths_or_protective_factors_yes_details:
    'health_wellbeing_practitioner_analysis_strengths_or_protective_factors_yes_details',
  health_wellbeing_practitioner_analysis_strengths_or_protective_factors_no_details:
    'health_wellbeing_practitioner_analysis_strengths_or_protective_factors_no_details',
  health_wellbeing_practitioner_analysis_strengths_or_protective_factors:
    'health_wellbeing_practitioner_analysis_strengths_or_protective_factors',
  health_wellbeing_practitioner_analysis_risk_of_serious_harm_yes_details:
    'health_wellbeing_practitioner_analysis_risk_of_serious_harm_yes_details',
  health_wellbeing_practitioner_analysis_risk_of_serious_harm_no_details:
    'health_wellbeing_practitioner_analysis_risk_of_serious_harm_no_details',
  health_wellbeing_practitioner_analysis_risk_of_serious_harm:
    'health_wellbeing_practitioner_analysis_risk_of_serious_harm',
  health_wellbeing_practitioner_analysis_risk_of_reoffending_yes_details:
    'health_wellbeing_practitioner_analysis_risk_of_reoffending_yes_details',
  health_wellbeing_practitioner_analysis_risk_of_reoffending_no_details:
    'health_wellbeing_practitioner_analysis_risk_of_reoffending_no_details',
  health_wellbeing_practitioner_analysis_risk_of_reoffending:
    'health_wellbeing_practitioner_analysis_risk_of_reoffending',
} as const
