export const Option = {
  sometimes: 'SOMETIMES',
  no_offending_activities: 'NO_OFFENDING_ACTIVITIES',
  sometimes_offending_activities: 'SOMETIMES_OFFENDING_ACTIVITIES',
  yes_offending_activities: 'YES_OFFENDING_ACTIVITIES',
  some: 'SOME',
  limited_problem_solving: 'LIMITED_PROBLEM_SOLVING',
  yes_offence_related_sexual_interest: 'YES_OFFENCE_RELATED_SEXUAL_INTEREST',
  some_offence_related_sexual_interest: 'SOME_OFFENCE_RELATED_SEXUAL_INTEREST',
  no_offence_related_sexual_interest: 'NO_OFFENCE_RELATED_SEXUAL_INTEREST',
  no_violence: 'NO_VIOLENCE',
  yes_violence: 'YES_VIOLENCE',
  yes_positive: 'YES_POSITIVE',
  negative_attitude_no_concerns: 'NEGATIVE_ATTITUDE_NO_CONCERNS',
  negative_attitude_and_concerns: 'NEGATIVE_ATTITUDE_AND_CONCERNS',
  yes_supervision: 'YES_SUPERVISION',
  unsure_supervision: 'UNSURE_SUPERVISION',
  no_supervision: 'NO_SUPERVISION',
} as const
