events {
}

http {
  server {
    listen 8080;

    resolver 127.0.0.11 valid=10s;

    set $hmpps_arns_assessment_platform_ui "hmpps-arns-assessment-platform-ui:8080";
    set $hmpps_arns_assessment_platform_api "hmpps-arns-assessment-platform-api:8080";
    set $hmpps_assess_risks_and_needs "hmpps-assess-risks-and-needs:8080";
    set $hmpps_assess_risks_and_needs_coordinator_api "hmpps-assess-risks-and-needs-coordinator-api:8080";
    set $hmpps_assess_risks_and_needs_handover_service "hmpps-assess-risks-and-needs-handover-service:8080";
    set $hmpps_auth "hmpps-auth:9090";
    set $hmpps_strengths_based_needs_assessments_api "hmpps-strengths-based-needs-assessments-api:8080";
    set $hmpps_strengths_based_needs_assessments_ui "hmpps-strengths-based-needs-assessments-ui:8080";

    proxy_set_header X-Forwarded-For   $host;
    proxy_set_header X-Forwarded-Proto $scheme;

    location /hmpps-arns-assessment-platform-ui/ {
        proxy_set_header Host $hmpps_arns_assessment_platform_ui;
        proxy_pass http://$hmpps_arns_assessment_platform_ui/;
        proxy_redirect / /hmpps-arns-assessment-platform-ui/;
    }

    location /hmpps-arns-assessment-platform-api/ {
        proxy_set_header Host $hmpps_arns_assessment_platform_api;
        proxy_pass http://$hmpps_arns_assessment_platform_api/;
        proxy_redirect / /hmpps-arns-assessment-platform-api/;
    }

    location /hmpps-assess-risks-and-needs/ {
        proxy_set_header Host $hmpps_assess_risks_and_needs;
        proxy_pass http://$hmpps_assess_risks_and_needs/;
        proxy_redirect / /hmpps-assess-risks-and-needs/;
    }

    location /hmpps-assess-risks-and-needs-coordinator-api/ {
        proxy_set_header Host $hmpps_assess_risks_and_needs_coordinator_api;
        proxy_pass http://$hmpps_assess_risks_and_needs_coordinator_api/;
        proxy_redirect / /hmpps-assess-risks-and-needs-coordinator-api/;
    }

    location /hmpps-assess-risks-and-needs-handover-service/ {
        proxy_set_header Host $hmpps_assess_risks_and_needs_handover_service;
        proxy_pass http://$hmpps_assess_risks_and_needs_handover_service/;
        proxy_redirect / /hmpps-assess-risks-and-needs-handover-service/;
    }

    location /hmpps-auth/ {
        proxy_set_header Host $hmpps_auth;
        proxy_pass http://$hmpps_auth/;
        proxy_redirect / /hmpps-auth/;
    }

    location /hmpps-strengths-based-needs-assessments-api/ {
        proxy_set_header Host $hmpps_strengths_based_needs_assessments_api;
        proxy_pass http://$hmpps_strengths_based_needs_assessments_api/;
        proxy_redirect / /hmpps-strengths-based-needs-assessments-api/;
    }

    location /hmpps-strengths-based-needs-assessments-ui/ {
        proxy_set_header Host $hmpps_strengths_based_needs_assessments_ui;
        proxy_pass http://$hmpps_strengths_based_needs_assessments_ui/;
        proxy_redirect / /hmpps-strengths-based-needs-assessments-ui/;
    }
  }
}
