export const Question = {
  personal_relationships_community_children_details: 'personal_relationships_community_children_details',
  personal_relationships_community_children_details_yes_children_living_with_pop_details:
    'personal_relationships_community_children_details_yes_children_living_with_pop_details',
  personal_relationships_community_children_details_yes_children_not_living_with_pop_details:
    'personal_relationships_community_children_details_yes_children_not_living_with_pop_details',
  personal_relationships_community_children_details_yes_children_visiting_details:
    'personal_relationships_community_children_details_yes_children_visiting_details',

  personal_relationships_community_important_people: 'personal_relationships_community_important_people',
  personal_relationships_community_important_people_partner_intimate_relationship_details:
    'personal_relationships_community_important_people_partner_intimate_relationship_details',
  personal_relationships_community_important_people_child_parental_responsibilities_details:
    'personal_relationships_community_important_people_child_parental_responsibilities_details',
  personal_relationships_community_important_people_other_children_details:
    'personal_relationships_community_important_people_other_children_details',
  personal_relationships_community_important_people_family_details:
    'personal_relationships_community_important_people_family_details',
  personal_relationships_community_important_people_friends_details:
    'personal_relationships_community_important_people_friends_details',
  personal_relationships_community_important_people_other_details:
    'personal_relationships_community_important_people_other_details',

  personal_relationships_community_current_relationship: 'personal_relationships_community_current_relationship',
  personal_relationships_community_current_relationship_happy_relationship_details:
    'personal_relationships_community_current_relationship_happy_relationship_details',
  personal_relationships_community_current_relationship_concerns_happy_relationship_details:
    'personal_relationships_community_current_relationship_concerns_happy_relationship_details',
  personal_relationships_community_current_relationship_unhappy_relationship_details:
    'personal_relationships_community_current_relationship_unhappy_relationship_details',

  personal_relationships_community_intimate_relationship: 'personal_relationships_community_intimate_relationship',
  personal_relationships_community_intimate_relationship_stable_relationships_details:
    'personal_relationships_community_intimate_relationship_stable_relationships_details',
  personal_relationships_community_intimate_relationship_positive_and_negative_relationships_details:
    'personal_relationships_community_intimate_relationship_positive_and_negative_relationships_details',
  personal_relationships_community_intimate_relationship_unstable_relationships_details:
    'personal_relationships_community_intimate_relationship_unstable_relationships_details',

  personal_relationships_community_challenges_intimate_relationship:
    'personal_relationships_community_challenges_intimate_relationship',

  personal_relationships_community_parental_responsibilities:
    'personal_relationships_community_parental_responsibilities',
  personal_relationships_community_parental_responsibilities_yes_details:
    'personal_relationships_community_parental_responsibilities_yes_details',
  personal_relationships_community_parental_responsibilities_sometimes_details:
    'personal_relationships_community_parental_responsibilities_sometimes_details',
  personal_relationships_community_parental_responsibilities_no_details:
    'personal_relationships_community_parental_responsibilities_no_details',

  personal_relationships_community_family_relationship: 'personal_relationships_community_family_relationship',
  personal_relationships_community_family_relationship_stable_relationship_details:
    'personal_relationships_community_family_relationship_stable_relationship_details',
  personal_relationships_community_family_relationship_mixed_relationship_details:
    'personal_relationships_community_family_relationship_mixed_relationship_details',
  personal_relationships_community_family_relationship_unstable_relationship_details:
    'personal_relationships_community_family_relationship_unstable_relationship_details',

  personal_relationships_community_childhood: 'personal_relationships_community_childhood',
  personal_relationships_community_childhood_positive_childhood_details:
    'personal_relationships_community_childhood_positive_childhood_details',
  personal_relationships_community_childhood_mixed_childhood_details:
    'personal_relationships_community_childhood_mixed_childhood_details',
  personal_relationships_community_childhood_negative_childhood_details:
    'personal_relationships_community_childhood_negative_childhood_details',

  personal_relationships_community_childhood_behaviour: 'personal_relationships_community_childhood_behaviour',
  personal_relationships_community_childhood_behaviour_yes_details:
    'personal_relationships_community_childhood_behaviour_yes_details',
  personal_relationships_community_childhood_behaviour_no_details:
    'personal_relationships_community_childhood_behaviour_no_details',

  personal_relationships_community_belonging: 'personal_relationships_community_belonging',

  personal_relationships_community_changes: 'personal_relationships_community_changes',
  personal_relationships_community_changes_made_changes_details:
    'personal_relationships_community_changes_made_changes_details',
  personal_relationships_community_changes_making_changes_details:
    'personal_relationships_community_changes_making_changes_details',
  personal_relationships_community_changes_want_to_make_changes_details:
    'personal_relationships_community_changes_want_to_make_changes_details',
  personal_relationships_community_changes_needs_help_to_make_changes_details:
    'personal_relationships_community_changes_needs_help_to_make_changes_details',
  personal_relationships_community_changes_thinking_about_making_changes_details:
    'personal_relationships_community_changes_thinking_about_making_changes_details',
  personal_relationships_community_changes_does_not_want_to_make_changes_details:
    'personal_relationships_community_changes_does_not_want_to_make_changes_details',
  personal_relationships_community_changes_does_not_want_to_answer_details:
    'personal_relationships_community_changes_does_not_want_to_answer_details',

  personal_relationships_community_practitioner_analysis_strengths_or_protective_factors:
    'personal_relationships_community_practitioner_analysis_strengths_or_protective_factors',
  personal_relationships_community_practitioner_analysis_strengths_or_protective_factors_yes_details:
    'personal_relationships_community_practitioner_analysis_strengths_or_protective_factors_yes_details',
  personal_relationships_community_practitioner_analysis_strengths_or_protective_factors_no_details:
    'personal_relationships_community_practitioner_analysis_strengths_or_protective_factors_no_details',

  personal_relationships_community_practitioner_analysis_risk_of_serious_harm:
    'personal_relationships_community_practitioner_analysis_risk_of_serious_harm',
  personal_relationships_community_practitioner_analysis_risk_of_serious_harm_yes_details:
    'personal_relationships_community_practitioner_analysis_risk_of_serious_harm_yes_details',
  personal_relationships_community_practitioner_analysis_risk_of_serious_harm_no_details:
    'personal_relationships_community_practitioner_analysis_risk_of_serious_harm_no_details',

  personal_relationships_community_practitioner_analysis_risk_of_reoffending:
    'personal_relationships_community_practitioner_analysis_risk_of_reoffending',
  personal_relationships_community_practitioner_analysis_risk_of_reoffending_yes_details:
    'personal_relationships_community_practitioner_analysis_risk_of_reoffending_yes_details',
  personal_relationships_community_practitioner_analysis_risk_of_reoffending_no_details:
    'personal_relationships_community_practitioner_analysis_risk_of_reoffending_no_details',
} as const
