export const Question = {
  personal_relationships_community_children_details: 'personal_relationships_community_children_details',
  personal_relationships_community_children_details_yes_children_living_with_pop_details:
    'personal_relationships_community_children_details_yes_children_living_with_pop_details',
  personal_relationships_community_children_details_yes_children_not_living_with_pop_details:
    'personal_relationships_community_children_details_yes_children_not_living_with_pop_details',
  personal_relationships_community_children_details_yes_children_visiting_details:
    'personal_relationships_community_children_details_yes_children_visiting_details',

  personal_relationships_community_important_people: 'personal_relationships_community_important_people',
  personal_relationships_community_family_relationship: 'personal_relationships_community_family_relationship',
  personal_relationships_community_childhood: 'personal_relationships_community_childhood',
  personal_relationships_community_childhood_behaviour: 'personal_relationships_community_childhood_behaviour',
  personal_relationships_community_belonging: 'personal_relationships_community_belonging',
  personal_relationships_community_parental_responsibilities:
    'personal_relationships_community_parental_responsibilities',
  personal_relationships_community_current_relationship: 'personal_relationships_community_current_relationship',
  personal_relationships_community_intimate_relationship: 'personal_relationships_community_intimate_relationship',
  personal_relationships_community_challenges_intimate_relationship:
    'personal_relationships_community_challenges_intimate_relationship',
  personal_relationships_community_changes: 'personal_relationships_community_changes',
}
