export const Option = {
  carers_allowance: 'CARERS_ALLOWANCE',
  disability_benefits: 'DISABILITY_BENEFITS',
  employment: 'EMPLOYMENT',
  family_or_friends: 'FAMILY_OR_FRIENDS',
  offending: 'OFFENDING',
  pension: 'PENSION',
  student_loan: 'STUDENT_LOAN',
  undeclared: 'UNDECLARED',
  work_related_benefits: 'WORK_RELATED_BENEFITS',
  no_money: 'NO_MONEY',
  good: 'GOOD',
  fairly_good: 'FAIRLY_GOOD',
  fairly_bad: 'FAIRLY_BAD',
  bad: 'BAD',
  yes_their_gambling: 'YES_THEIR_GAMBLING',
  yes_someone_elses_gambling: 'YES_SOMEONE_ELSES_GAMBLING',
  yes_their_debt: 'YES_THEIR_DEBT',
  yes_someone_elses_debt: 'YES_SOMEONE_ELSES_DEBT',
  debt_to_others: 'DEBT_TO_OTHERS',
  formal_debt: 'FORMAL_DEBT',
} as const
