export const Question = {
  finance_income: 'finance_income',
  finance_income_no_money_details: 'finance_income_no_money_details',
  finance_income_other_details: 'finance_income_other_details',
  finance_income_family_or_friends_details: 'finance_income_family_or_friends_details',
  finance_bank_account: 'finance_bank_account',
  finance_money_management: 'finance_money_management',
  finance_money_management_good_details: 'finance_money_management_good_details',
  finance_money_management_fairly_good_details: 'finance_money_management_fairly_good_details',
  finance_money_management_fairly_bad_details: 'finance_money_management_fairly_bad_details',
  finance_money_management_bad_details: 'finance_money_management_bad_details',
  finance_gambling: 'finance_gambling',
  finance_gambling_yes_their_gambling_details: 'finance_gambling_yes_their_gambling_details',
  finance_gambling_yes_someone_elses_gambling_details: 'finance_gambling_yes_someone_elses_gambling_details',
  finance_gambling_unknown_details: 'finance_gambling_unknown_details',
  finance_debt: 'finance_debt',
  finance_debt_yes_their_debt: 'finance_debt_yes_their_debt',
  finance_debt_yes_someone_elses_debt: 'finance_debt_yes_someone_elses_debt',
  finance_debt_unknown_details: 'finance_debt_unknown_details',
  yes_their_debt_debt_to_others_details: 'yes_their_debt_to_others_details',
  yes_their_debt_formal_debt_details: 'yes_their_debt_formal_debt_details',
  yes_someone_elses_debt_debt_to_others_details: 'yes_someone_elses_debt_to_others_details',
  yes_someone_elses_debt_formal_debt_details: 'yes_someone_elses_debt_to_others_details',
  finance_changes: 'finance_changes',
  finance_changes_has_made_changes_details: 'finance_changes_has_made_changes_details',
  finance_changes_is_making_changes_details: 'finance_changes_is_making_changes_details',
  finance_changes_wants_to_make_changes_knows_how_to_details:
    'finance_changes_wants_to_make_changes_knows_how_to_details',
  finance_changes_wants_to_make_changes_needs_help_details: 'finance_changes_wants_to_make_changes_needs_help_details',
  finance_changes_thinking_about_making_changes_details: 'finance_changes_thinking_about_making_changes_details',
  finance_changes_does_not_want_to_make_changes_details: 'finance_changes_does_not_want_to_make_changes_details',
  finance_changes_does_not_want_to_answer_details: 'finance_changes_does_not_want_to_answer_details',
  finance_strengths_protective_factors_details: 'finance_strengths_protective_factors_details',
  finance_no_strengths_protective_factors_details: 'finance_no_strengths_protective_factors_details',
  finance_strengths_protective_factors: 'finance_strengths_protective_factors',
  finance_linked_to_serious_harm: 'finance_linked_to_serious_harm',
  finance_serious_harm_details: 'finance_serious_harm_details',
  finance_no_serious_harm_details: 'finance_no_serious_harm_details',
  finance_linked_to_reoffending: 'finance_linked_to_reoffending',
  finance_risk_of_reoffending_details: 'finance_risk_of_reoffending_details',
  finance_no_risk_of_reoffending_details: 'finance_no_risk_of_reoffending_details',
} as const
